# Generated by Django 4.0.5 on 2023-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripetest', '0005_order_discount_amount_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
