# Generated by Django 4.0.5 on 2023-03-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripetest', '0008_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Order name here...', max_length=100),
        ),
    ]
